<!DOCTYPE html><html lang='en'><head><title>[except.terminate]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='icon' href='icon.png'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>15</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:88pt'>15.5</a> Special functions <a class='abbr_ref' href='except.special#except.terminate'>[except.special]</a></h2><div id='except.terminate'><h3 ><a class='secnum' style='min-width:103pt'>15.5.1</a> The <span class='texttt'>std&#x200b;::&#x200b;terminate()</span> function <a class='abbr_ref'>[except.terminate]</a></h3><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/5bc5cbae28d9e741ebc7df996f1f0d230ac4087e/source/exceptions.tex#L988'>#</a></div><p ><span class='indexparent'><a class='index' id='terminate'></a></span>In some situations exception handling must be abandoned
for less subtle error handling techniques. [<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Note:</span>  These situations are:</p><p ><span class='indexparent'><a class='index' id='terminate,called'></a></span></p><ul class='itemize'><li id='1.1'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.1'>(1.1)</a></div><p >when the exception handling mechanism, after completing
the initialization of the exception object
but before
activation of a handler for the exception (<a href='except.throw'>[except.throw]</a>),
calls a function that exits
via an exception, or</p></li><li id='1.2'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.2'>(1.2)</a></div><p >when the exception handling mechanism cannot find a handler for a thrown exception (<a href='except.handle'>[except.handle]</a>), or</p></li><li id='1.3'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.3'>(1.3)</a></div><p >when the search for a <a href='except.handle'>handler</a> encounters the
outermost block of a function
with a non-throwing <a href='except.spec'>exception specification</a>, or</p></li><li id='1.4'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.4'>(1.4)</a></div><p >when the destruction of an object during <a href='except.ctor#def:stack_unwinding'>stack unwinding</a>
terminates by throwing an exception, or</p></li><li id='1.5'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.5'>(1.5)</a></div><p >when initialization of a non-local
variable with static or thread storage duration (<a href='basic.start.dynamic'>[basic.start.dynamic]</a>)
exits via an exception, or</p></li><li id='1.6'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.6'>(1.6)</a></div><p >when destruction of an object with static or thread storage duration exits
via an exception (<a href='basic.start.term'>[basic.start.term]</a>), or</p></li><li id='1.7'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.7'>(1.7)</a></div><p >when execution of a function registered with
<span class='texttt'>std&#x200b;::&#x200b;atexit</span> or <span class='texttt'>std&#x200b;::&#x200b;at_&shy;quick_&shy;exit</span>
exits via an exception (<a href='support.start.term'>[support.start.term]</a>), or</p></li><li id='1.8'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.8'>(1.8)</a></div><p >when a
<i ><a href='expr.throw#nt:throw-expression'>throw-expression</a></i>
with no operand attempts to rethrow an exception and no exception is being
handled (<a href='except.throw'>[except.throw]</a>), or</p></li><li id='1.9'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.9'>(1.9)</a></div><p >when the function <span class='texttt'>std&#x200b;::&#x200b;nested_&shy;exception&#x200b;::&#x200b;rethrow_&shy;nested</span> is called for an object
that has captured no exception (<a href='except.nested'>[except.nested]</a>), or</p></li><li id='1.10'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.10'>(1.10)</a></div><p >when execution of the initial function of a thread exits via
an exception (<a href='thread.thread.constr'>[thread.thread.constr]</a>), or</p></li><li id='1.11'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.11'>(1.11)</a></div><p >for a parallel algorithm whose <span class='texttt'>ExecutionPolicy</span> specifies such
behavior (<a href='execpol.seq'>[execpol.seq]</a>, <a href='execpol.par'>[execpol.par]</a>, <a href='execpol.parunseq'>[execpol.parunseq]</a>),
when execution of an element access function (<a href='algorithms.parallel.defns'>[algorithms.parallel.defns]</a>)
of the parallel algorithm exits via an exception (<a href='algorithms.parallel.exceptions'>[algorithms.parallel.exceptions]</a>), or</p></li><li id='1.12'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.12'>(1.12)</a></div><p >when the destructor or the copy assignment operator is invoked on an object
of type <span class='texttt'>std&#x200b;::&#x200b;thread</span> that refers to a joinable thread
(<a href='thread.thread.destr'>[thread.thread.destr]</a>, <a href='thread.thread.assign'>[thread.thread.assign]</a>), or</p></li><li id='1.13'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#1.13'>(1.13)</a></div><p >when a call to a <span class='texttt'>wait()</span>, <span class='texttt'>wait_&shy;until()</span>, or <span class='texttt'>wait_&shy;for()</span>
function on a condition variable (<a href='thread.condition.condvar'>[thread.condition.condvar]</a>, <a href='thread.condition.condvarany'>[thread.condition.condvarany]</a>)
fails to meet a postcondition.</p></li></ul><p ><span class='textit'><span style='white-space:nowrap'>&thinsp;</span>â€”<span style='white-space:nowrap'>&thinsp;</span>end note</span><span style='white-space:nowrap'>&thinsp;</span>] </p></div><div class='para' id='2'><div class='marginalizedparent'><a class='marginalized' href='#2'>2</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/5bc5cbae28d9e741ebc7df996f1f0d230ac4087e/source/exceptions.tex#L1062'>#</a></div><p ><span class='indexparent'><a class='index' id='terminate'></a></span>In such cases,
<a href='exception.terminate'><span class='texttt'>std&#x200b;::&#x200b;terminate()</span>
is called</a>.
In the situation where no matching handler is found, it is
<span class='indexparent'><a class='index' id='stack_unwinding_before_call_to_std::terminate()'></a></span>implementation-defined whether or not the
stack is unwound
before
<span class='texttt'>std&#x200b;::&#x200b;terminate()</span>
is called.
In the situation where the search for a <a href='except.handle'>handler</a> encounters the
outermost block of a function
with a non-throwing <a href='except.spec'>exception specification</a>, it is
<span class='indexparent'><a class='index' id='whether_stack_is_unwound_before_calling_std::terminate()_when_a_noexcept_specification_is_violated'></a></span>implementation-defined
whether the stack is unwound, unwound partially, or not unwound at all
before <span class='texttt'>std&#x200b;::&#x200b;terminate()</span> is called.
In all other situations, the stack shall not be unwound before
<span class='texttt'>std&#x200b;::&#x200b;terminate()</span>
is called.
An implementation is not permitted to finish stack unwinding
prematurely based on a determination that the unwind process
will eventually cause a call to
<span class='texttt'>std&#x200b;::&#x200b;terminate()</span>.</p></div></div></div></body></html>