<!DOCTYPE html><html lang='en'><head><title>[expr.throw]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>5</a> Expressions <a class='abbr_ref' href='./#expr'>[expr]</a></h1><div id='expr.throw'><h2 ><a class='secnum' style='min-width:88pt'>5.17</a> Throwing an exception <a class='abbr_ref'>[expr.throw]</a></h2><p ><span class='indexparent'><a class='index' id='expression,throw'></a></span><span class='indexparent'><a class='index' id='exception_handling,throwing'></a></span><span class='indexparent'><a class='index' id='throw'></a></span></p><pre class='bnf'><a id='nt:throw-expression'>throw-expression:</a>
    <span class='terminal'>throw</span>  <i ><a href='expr.ass#nt:assignment-expression'>assignment-expression</a></i><span class='math'><sub ><span class='mathit'>opt</span></sub></span></pre><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><p >A <i ><a href='expr.throw#nt:throw-expression'>throw-expression</a></i> is of type <span class='texttt'>void</span>.</p></div><div class='para' id='2'><div class='marginalizedparent'><a class='marginalized' href='#2'>2</a></div><p >Evaluating a <i ><a href='expr.throw#nt:throw-expression'>throw-expression</a></i> with an operand throws an
exception (<a href='except.throw'>[except.throw]</a>); the type of the exception object is determined by removing
any top-level <span class='grammarterm'>cv-qualifiers</span> from the static type of the
operand and adjusting the type
from “array of <span class='texttt'>T</span>” or function type <span class='texttt'>T</span>
to “pointer to <span class='texttt'>T</span>”.</p></div><div class='para' id='3'><div class='marginalizedparent'><a class='marginalized' href='#3'>3</a></div><p ><span class='indexparent'><a class='index' id='exception_handling,rethrow'></a></span>A
<i ><a href='expr.throw#nt:throw-expression'>throw-expression</a></i>
with no operand rethrows the currently handled exception (<a href='except.handle'>[except.handle]</a>).
The exception is reactivated with the existing exception object;
no new exception object is created.
The exception is no longer considered to be caught.
[&nbsp;<i>Example:</i>
Code that must be executed because of an exception, but cannot
completely handle the exception itself, can be written like this:
</p><pre class='codeblock'>
try {
    <span class='comment'>// ...
</span>} catch (...) {     <span class='comment'>// catch all exceptions
</span>  <span class='comment'>// respond (partially) to exception
</span>  throw;            <span class='comment'>// pass the exception to some
</span>                    <span class='comment'>// other handler
</span>}
</pre><p ><i>&nbsp;—&nbsp;end example</i>&nbsp;]</p></div><div class='para' id='4'><div class='marginalizedparent'><a class='marginalized' href='#4'>4</a></div><p ><span class='indexparent'><a class='index' id='exception_handling,rethrow'></a></span><span class='indexparent'><a class='index' id='exception_handling,terminate_called'></a></span><span class='indexparent'><a class='index' id='terminate,called'></a></span>If no exception is presently being handled,
evaluating a
<i ><a href='expr.throw#nt:throw-expression'>throw-expression</a></i>
with no operand calls
<span class='texttt'>std::terminate()</span> (<a href='except.terminate'>[except.terminate]</a>).</p></div></div></div></body></html>