<!DOCTYPE html><html lang='en'><head><title>[except.uncaught]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>15</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:88pt'>15.5</a> Special functions <a class='abbr_ref' href='except.special#except.uncaught'>[except.special]</a></h2><div id='except.uncaught'><h3 ><a class='secnum' style='min-width:103pt'>15.5.3</a> The <span class='texttt'>std::uncaught_exception()</span> function <a class='abbr_ref'>[except.uncaught]</a></h3><p ><span class='indexparent'><a class='index' id='uncaught_exception()'></a></span></p><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><p >The function
<span class='texttt'>std::uncaught_exception()</span>
returns
<span class='texttt'>true</span>
after completing
the initialization of the exception object (<a href='except.throw'>[except.throw]</a>)
until completing
the
activation of a handler for the exception (<a href='except.handle'>[except.handle]</a>, <a href='uncaught'>[uncaught]</a>).
This includes stack unwinding.
If the exception is rethrown (<a href='except.throw'>[except.throw]</a>),
<span class='texttt'>std::uncaught_exception()</span>
returns
<span class='texttt'>true</span>
from the point of rethrow until the rethrown exception is caught again.<span class='indexparent'><a class='index' id='exception_handling'></a></span>
</p></div></div></div></body></html>