<!DOCTYPE html><html lang='en'><head><title>[except.ctor]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>15</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><div id='except.ctor'><h2 ><a class='secnum' style='min-width:88pt'>15.2</a> Constructors and destructors <a class='abbr_ref'>[except.ctor]</a></h2><p ><span class='indexparent'><a class='index' id='exception_handling,constructors_and_destructors'></a></span><span class='indexparent'><a class='index' id='stack_unwinding,see_exception_handling,_constructors_and_destructors'></a></span><span class='indexparent'><a class='index' id='constructor,exception_handling'></a></span><span class='indexparent'><a class='index' id='destructor,exception_handling'></a></span></p><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><p >As control passes from the point where an exception is thrown
to a handler,
destructors are invoked for all automatic objects constructed since the
try block was entered.
The automatic objects are destroyed in the reverse order of the completion
of their construction.</p></div><div class='para' id='2'><div class='marginalizedparent'><a class='marginalized' href='#2'>2</a></div><p >An object
of any storage duration whose initialization or destruction is terminated by an exception
will have
destructors executed for all of its fully constructed
subobjects (excluding the variant members of a union-like class),
that is, for subobjects for which the principal
constructor (<a href='class.base.init'>[class.base.init]</a>) has completed execution
and the destructor has not yet begun execution.
Similarly, if the non-delegating constructor for an object has
completed execution and a delegating constructor for that object exits with
an exception, the object's destructor will be invoked.
If the object was allocated in a
<i ><a href='expr.new#nt:new-expression'>new-expression</a></i>,
the matching deallocation function (<a href='basic.stc.dynamic.deallocation'>[basic.stc.dynamic.deallocation]</a>, <a href='expr.new'>[expr.new]</a>, <a href='class.free'>[class.free]</a>),
if any, is called to free the storage occupied by the
object.</p></div><div class='para' id='3'><div class='marginalizedparent'><a class='marginalized' href='#3'>3</a></div><p ><span class='indexparent'><a class='index' id='unwinding,stack'></a></span>The process of calling destructors for automatic objects constructed on the
path from a try block to the point where an exception is thrown
is called
“<a class='hidden_link' href='#def:stack_unwinding' id='def:stack_unwinding'><i>stack unwinding</i></a>.”
If a destructor called during stack unwinding exits with an exception,
<span class='texttt'>std::terminate</span>
is called (<a href='except.terminate'>[except.terminate]</a>).
[&nbsp;<i>Note:</i>
So destructors should generally catch
exceptions and not let them propagate out of the destructor.
<i>&nbsp;—&nbsp;end note</i>&nbsp;]</p></div></div></div></body></html>